world_frame: "map"
odom_frame: "odom"
rover_frame: "base_link"
use_odom_frame: true

gps_linearization:
  reference_point_latitude: 38.3662183
  reference_point_longitude: -110.91584383
  reference_point_altitude: 1300
