# VMWare Fusion requires an elevated kernel version to enable graphical acceleration
# This makes a big difference in running the simulator

- name: Add Mesa PPA
  become: true
  apt_repository:
    repo: ppa:kisak/kisak-mesa

- name: Add Mainline Kernel PPA
  become: true
  apt_repository:
    repo: ppa:cappelikan/ppa

- name: Install APT Packages
  become: true
  apt:
    cache_valid_time: 604800
    state: latest
    name:
      - mainline

# This upgrades existing Mesa packages
- name: Upgrade APT Packages
  apt:
    upgrade: yes

- name: Install Mainline Kernel
  become: true
  command: mainline --install-latest

# mainline leaves apt in a broken state which is annoying
- name: Fix Broken APT
  become: true
  command: apt --fix-broken install -y
